# Generated by Django 4.2.23 on 2025-06-17 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('goal_type', models.CharField(choices=[('technique', 'Technique'), ('repertoire', 'Repertoire'), ('routine', 'Routine'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('target_tempo', models.PositiveIntegerField(blank=True, null=True)),
                ('target_accuracy', models.FloatField(blank=True, null=True)),
                ('target_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('routine_target_days', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StandardGoalDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('goal_type', models.CharField(choices=[('technique', 'Technique'), ('repertoire', 'Repertoire'), ('routine', 'Routine'), ('custom', 'Custom')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StandardPracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('goal_type', models.CharField(choices=[('technique', 'Technique'), ('repertoire', 'Repertoire'), ('routine', 'Routine'), ('custom', 'Custom')], default='custom', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('tempo', models.PositiveIntegerField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='Accuracy as percentage (0–100)', null=True)),
                ('notes', models.TextField(blank=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='practice.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='standard_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='practice.standardgoaldefinition'),
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL),
        ),
    ]
