# Generated by Django 4.2.23 on 2025-06-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StandardPracticeSession',
        ),
    ]
