# Generated by Django 4.2.23 on 2025-06-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='metrics',
            field=models.JSONField(blank=True, help_text='Dict of target values for selected metrics (e.g. {"tempo": 120, "mistakes": 0})', null=True),
        ),
    ]
