# Generated by Django 4.2.23 on 2025-06-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_goal_metrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicesession',
            name='progress_percent',
        ),
        migrations.AddField(
            model_name='goal',
            name='start_tempo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='metrics',
            field=models.JSONField(blank=True, help_text='Dict of target values for selected metrics (e.g. {"tempo": 120, "mistakes": 0, "duration": 300})', null=True),
        ),
    ]
