# Generated by Django 4.2.23 on 2025-06-18 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_delete_standardpracticesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgoals', to='practice.goal'),
        ),
    ]
